# Generated by Django 5.2.8 on 2025-12-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='metal_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_grams',
        ),
        migrations.AddField(
            model_name='product',
            name='metal',
            field=models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Platinum', 'Platinum'), ('Rose Gold', 'Rose Gold'), ('Brass', 'Brass')], max_length=100),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='store_produ_name_5e57da_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created'], name='store_produ_created_ca958a_idx'),
        ),
    ]
