# Generated by Django 5.2.8 on 2025-12-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_adjustable',
            field=models.BooleanField(default=False, verbose_name='Is Adjustable Ring'),
        ),
    ]
