# Generated by Django 5.2.8 on 2025-12-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('primary_color', models.CharField(default='#000000', help_text='Main brand color (Buttons, Prices)', max_length=7)),
                ('text_color', models.CharField(default='#171717', help_text='Body text color', max_length=7)),
                ('bg_color', models.CharField(default='#ffffff', help_text='Page background color', max_length=7)),
                ('accent_color', models.CharField(default='#D4AF37', help_text='Highlights, links hover', max_length=7)),
                ('promo_bg', models.CharField(default='#452829', help_text='Promo bar background', max_length=7)),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
            },
        ),
    ]
