# Generated by Django 5.2.8 on 2025-12-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='button_bg_color',
            field=models.CharField(default='#000000', help_text='Button background color (Add to Cart)', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='button_hover_bg_color',
            field=models.CharField(default='#333333', help_text='Button hover background color', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='button_text_color',
            field=models.CharField(default='#ffffff', help_text='Button text color', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='buy_now_bg_color',
            field=models.CharField(default='#ffffff', help_text='Buy Now background color', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='buy_now_hover_bg_color',
            field=models.CharField(default='#000000', help_text='Buy Now hover background color', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='buy_now_hover_text_color',
            field=models.CharField(default='#ffffff', help_text='Buy Now hover text color', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='buy_now_text_color',
            field=models.CharField(default='#000000', help_text='Buy Now text color', max_length=7),
        ),
    ]
