# Generated by Django 5.2.8 on 2025-12-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_theme_button_bg_color_theme_button_hover_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed discount amount in TK', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount (0-100). Takes priority over fixed amount.', max_digits=5, null=True),
        ),
    ]
