# Generated by Django 5.2.8 on 2025-12-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_discount_amount_product_discount_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for this configuration', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Only one hero can be active at a time')),
                ('background_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Choose between image or video background', max_length=10)),
                ('background_image', models.ImageField(blank=True, help_text='Upload an image (PNG, JPG, GIF). Recommended: 1920x1080 or higher', null=True, upload_to='hero/')),
                ('background_video', models.FileField(blank=True, help_text='Upload a video (MP4, WEBM). Keep under 10MB for best performance', null=True, upload_to='hero/videos/')),
                ('logo', models.FileField(blank=True, help_text='Upload SVG or image logo for hero section', null=True, upload_to='hero/logos/')),
                ('headline', models.CharField(blank=True, help_text='Optional main headline text', max_length=200)),
                ('tagline', models.CharField(blank=True, default='Every Piece of Jewelry has a story to tell', help_text='Subtitle text below the logo', max_length=300)),
                ('show_logo', models.BooleanField(default=True, help_text='Show the logo in hero section')),
                ('show_headline', models.BooleanField(default=False, help_text='Show the headline text')),
                ('show_tagline', models.BooleanField(default=True, help_text='Show the tagline text')),
                ('enable_ken_burns', models.BooleanField(default=True, help_text='Enable Ken Burns zoom animation for image backgrounds')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['-is_active', '-updated'],
            },
        ),
    ]
