# Generated by Django 6.0 on 2025-12-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_herosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='list_image_fit',
            field=models.CharField(choices=[('cover', 'Cover (Crop to fit)'), ('contain', 'Contain (Show full)')], default='cover', max_length=20, verbose_name='List Image Sizing'),
        ),
        migrations.AddField(
            model_name='product',
            name='list_image_position',
            field=models.CharField(choices=[('center center', 'Center (Default)'), ('top center', 'Top'), ('bottom center', 'Bottom'), ('center left', 'Left'), ('center right', 'Right')], default='center center', max_length=20, verbose_name='List Image Position'),
        ),
    ]
