# Generated by Django 6.0 on 2025-12-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_list_image_fit_product_list_image_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='mobile_background_image',
            field=models.ImageField(blank=True, help_text='Upload a vertical image for mobile (e.g., 1080x1920).', null=True, upload_to='hero/mobile/'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mobile_background_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Choose background type for mobile devices', max_length=10),
        ),
        migrations.AddField(
            model_name='herosection',
            name='mobile_background_video',
            field=models.FileField(blank=True, help_text='Upload a vertical video for mobile.', null=True, upload_to='hero/mobile/videos/'),
        ),
    ]
