# Generated by Django 5.2.8 on 2025-12-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
