# Generated by Django 5.2.8 on 2025-12-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_bkash_number_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', help_text='11-digit mobile number', max_length=11),
        ),
    ]
