# Generated by Django 5.2.8 on 2025-12-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_zone',
            field=models.CharField(choices=[('inside_dhaka', 'Inside Dhaka (80 TK)'), ('intercity_dhaka', 'Intercity Dhaka (120 TK)'), ('outside_dhaka', 'Outside Dhaka (150 TK)')], default='inside_dhaka', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
