# Generated by Django 5.2.8 on 2025-12-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_shipping_zone_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bkash_number',
            field=models.CharField(blank=True, help_text='The number you sent money from (bKash/Nagad)', max_length=11, null=True),
        ),
    ]
