# Generated by Django 5.2.8 on 2025-12-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pathao_area_id',
            field=models.IntegerField(blank=True, help_text='Pathao Area ID for delivery', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_city_id',
            field=models.IntegerField(blank=True, help_text='Pathao City ID for delivery', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_consignment_id',
            field=models.CharField(blank=True, help_text='Pathao tracking/consignment ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_order_status',
            field=models.CharField(blank=True, help_text='Order status from Pathao', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_zone_id',
            field=models.IntegerField(blank=True, help_text='Pathao Zone ID for delivery', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sent_to_pathao',
            field=models.BooleanField(default=False, help_text='Whether this order has been sent to Pathao'),
        ),
    ]
