# Generated by Django 5.2.8 on 2025-12-20 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_pathao_area_id_order_pathao_city_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathaoCity',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('city_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pathao City',
                'verbose_name_plural': 'Pathao Cities',
                'ordering': ['city_name'],
            },
        ),
        migrations.CreateModel(
            name='PathaoZone',
            fields=[
                ('zone_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('zone_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='orders.pathaocity')),
            ],
            options={
                'verbose_name': 'Pathao Zone',
                'verbose_name_plural': 'Pathao Zones',
                'ordering': ['zone_name'],
            },
        ),
        migrations.CreateModel(
            name='PathaoArea',
            fields=[
                ('area_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('area_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='orders.pathaozone')),
            ],
            options={
                'verbose_name': 'Pathao Area',
                'verbose_name_plural': 'Pathao Areas',
                'ordering': ['area_name'],
            },
        ),
    ]
