# Generated by Django 6.0 on 2025-12-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderitem_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount for mobile payment methods', max_digits=10),
        ),
    ]
